### PR TITLE
Add Sonatype configuration

### PR DESCRIPTION
**Pull request by srstevenson**

### CODE REVIEW

**Comment by pbugnion** [comment]
Interesting -- for the Plotly client, sonatype.sbt is all in XML. I didn't know you could write it with Scala types.

```
sonatypeProfileName := "co.theasi"

// For Maven Central
pomExtra in Global := {
  <url>https://github.com/ASIDataScience/plotly-client</url>
  <licenses>
    <license>
      <name>MIT</name>
      <url>https://opensource.org/licenses/MIT</url>
    </license>
  </licenses>
  <scm>
    <connection>scm:git:github.com/ASIDataScience/plotly-client</connection>
    <developerConnection>scm:git:git@github.com:ASIDataScience/plotly-client</developerConnection>
    <url>github.com/ASIDataScience/plotly-client</url>
  </scm>
  <developers>
    <developer>
      <id>pbugnion</id>
      <name>Pascal Bugnion</name>
      <url>pascalbugnion.net</url>
    </developer>
  </developers>
}
```

**Comment by pbugnion** [comment]
A couple of things that would be useful to discuss (but not necessarily sort out for this PR):

 - are we keeping git versions or reverting to the more common `0.1.0-snapshot`? I think it's somewhat cleaner to keep git versions.
 - if we keep git versions, we should have a way to automatically deploy on merge, maybe as part of a deployment step on Travis?
 - we should show the latest version on the README (ideally updating in some automated way?)

**Comment by srstevenson** [comment]
> - are we keeping git versions or reverting to the more common `0.1.0-snapshot`? I think it's somewhat cleaner to keep git versions.
> - if so, I don't *think* we can use `isSnapshot` to determine whether a release should go to sonatypes snapshot or staging. For instance: tag `0.1.3+gabcde123` shouldn't go to Maven Central, but it's also not a snapshot.
> - if we keep git versions, we should have a way to automatically deploy on merge, maybe as part of a deployment step on Travis?
> - we should show the latest version on the README (ideally updating in some automated way?)

@pbugnion Which of these do you consider blockers for this PR?

**Comment by pbugnion** [comment]
I think all these problems go away if we just revert to using manual versioning, rather than relying on git versions (ie, we remove the git-sbt plugin).

**Comment by srstevenson** [comment]
@pbugnion I've removed the Git plugin, reverted to manual versioning, and rebased this on master. Can you take another look?

**Comment by srstevenson** [comment]
Bump.

**Comment by pbugnion** [comment]
This is fine afaict, and it'd definitely be good to have this on sonatype rather than our own private S3 bucket. Have we actually tested that pushing this to sonatype works?

**Comment by srstevenson** [comment]
Yes, I've pushed 0.3.1 to Sonatype and the artefacts are [here](https://repo1.maven.org/maven2/com/asidatascience/dynamic-configuration_2.11/0.3.1/). We didn't originally have `publishMavenStyle := true` set, so this doesn't show on https://search.maven.org/, but I've added that configuration in [`8c95a3`](https://github.com/ASIDataScience/dynamic-configuration/pull/16/commits/8c95a3836b772ec0c0134ef2ee785a26fb08f1f6) for future releases.

**Comment by pbugnion** [comment]
ah perfect. In this case, let's definitely merge this.

**Pull request merged**
