### PR TITLE
Warn on compile and error on Travis CI if code is malformatted

### PR DESCRIPTION
**Pull request by srstevenson**
This ensures a consistent style, without having to think about it again.

### CODE REVIEW

**Comment by pbugnion** [comment]
I haven't found any open source project that uses scalafmt as part of the compilation step (I looked at scala-csv, play-json, json4s and scalaj-http). Most of them seem to rely on scalariform and compiler warnings. I think that the rationale against using scalafmt internally also applies here: people find it surprising.

You've put more work into this repo than I have, so your call.

**Comment by srstevenson** [comment]
> Most of them seem to rely on scalariform and compiler warnings.

I tried out Scalariform too, but found Scalafmt to give (subjectively) better results: the Scalafmt author lists the advantages he perceives in the [Scalafmt FAQs](http://scalameta.org/scalafmt/#WhynotScalariform?). I'd argue Scalafmt serves a different purpose than compiler warnings: ensuring a consistent, legible style by formatting the whole codebase with a single algorithm, whereas compiler warnings indicate code with possibly unintended behaviour. The former can be achieved automatically, whereas the latter requires the programmer's understanding of what the code should do.

> I think that the rationale against using scalafmt internally also applies here: people find it surprising.

Is your concern more about the requirement to format code with Scalafmt, or specifically including it's execution in the `compile` task? I'm not wedded to the latter: it just seemed the best way to ensure it was run without additional cognitive burden on the programmer.

**Comment by pbugnion** [comment]
> Is your concern more about the requirement to format code with Scalafmt, or specifically including its execution in the compile task? 

Specifically including its execution in the compile task.

I think forcing people to run the code through scalafmt before submitting PRs is a really good thing for all the reasons that you said. I'm just not sure whether the right way is through convention (e.g. by writing it in the CONTRIBUTING guide and in a PR template) or through code. Could we check scalafmt as a Travis step?

**Comment by srstevenson** [comment]
@pbugnion I've updated the changes so now Scalafmt emits warnings during the `compile` task if there is code that hasn't been formatted, but doesn't automatically format it. The Travis CI build will fail if there is unformatted code.

**Comment by srstevenson** [comment]
@pbugnion bump.

**Comment by pbugnion** [comment]
I think that looks good. Merge when you're ready.

**Pull request merged**
